#!/usr/bin/env python3
"""Generate the master ID translation map for Cửu Đỉnh (Vietnamese -> English slugs)."""

import json, re

# ---------------------------------------------------------------------------
# items (linh-khi.csv) -- 78
# ---------------------------------------------------------------------------
items = {
    # Kim (metal)
    "chuong-dong": "bronze-bell",
    "kiem-co-bach-ho": "white-tiger-sword",
    "nghien-muc-kim-tinh": "metal-essence-inkstone",
    "chau-bach-ho": "white-tiger-bead",
    "dao-co-sac": "ancient-keen-saber",
    "tuong-bach-ho": "white-tiger-statue",
    "phu-kim-tu": "metal-rune-talisman",
    "dinh-bach-kim": "platinum-cauldron",
    "hop-co-kim-khi": "ancient-metal-box",
    "quat-bach-tinh": "silver-star-fan",
    # Mộc (wood)
    "canh-bo-de": "bodhi-branch",
    "den-la-sen": "lotus-leaf-lantern",
    "bua-truong-sinh": "longevity-talisman",
    "tuong-thanh-long": "azure-dragon-statue",
    "chau-thanh-long": "azure-dragon-bead",
    "hoa-sen-linh": "spirit-lotus-flower",
    "binh-cam-lo-xanh": "green-nectar-vase",
    "cay-trau-co": "ancient-betel-branch",
    "dinh-luc-bao": "jade-cauldron",
    "quat-truc-co": "ancient-bamboo-fan",
    # Thuỷ (water)
    "binh-cam-lo-den": "dark-nectar-vase",
    "chau-thuy-long": "water-dragon-bead",
    "den-bang": "ice-lantern",
    "tuong-hac-quy": "black-tortoise-statue",
    "bua-hai-long": "sea-dragon-talisman",
    "nghien-muc-han-bang": "frost-ice-inkstone",
    "kiem-luu-bang": "flowing-ice-sword",
    "dinh-hac-bich": "black-jade-cauldron",
    "hop-han-khi": "frost-qi-box",
    "quat-hac-phung": "black-phoenix-fan",
    # Hoả (fire)
    "den-long-do": "red-lantern",
    "bua-phuong-linh": "phoenix-spirit-talisman",
    "tuong-chu-tuoc": "vermilion-bird-statue",
    "chau-hoa-phuong": "fire-phoenix-bead",
    "kiem-hoa-long": "fire-dragon-sword",
    "dinh-do-son": "vermilion-cauldron",
    "quat-phong-hoa": "fire-wind-fan",
    "nghien-muc-do": "red-inkstone",
    "hop-hoa-tinh": "fire-essence-box",
    "binh-hoa-chau": "fire-bead-vase",
    # Thổ (earth)
    "da-co": "ancient-stone-cauldron",
    "tuong-hoang-lan": "yellow-qilin-statue",
    "chau-hoang-tho": "yellow-earth-bead",
    "bua-tran-yeu": "demon-ward-talisman",
    "hop-dat-co": "ancient-earth-box",
    "dinh-tram-huong": "agarwood-cauldron",
    "quat-hoang-sa": "yellow-sand-fan",
    "tuong-tho": "earth-wall-statue",
    "nghien-muc-hoang": "yellow-inkstone",
    "den-dat": "earth-lantern",
    # Vô Cực (void)
    "bua-vo-tu": "wordless-talisman",
    "tuong-vo-dien": "faceless-statue",
    "chau-hon-nguyen": "primordial-chaos-bead",
    "hop-vo-cuc": "void-box",
    "den-vo-linh": "spiritless-lantern",
    "kiem-vo-cuc": "void-sword",
    "dinh-hon-nguyen": "primordial-chaos-cauldron",
    "nghien-muc-bi-canh": "secret-realm-inkstone",
    "quat-vo-hinh": "formless-fan",
    "binh-hon-dan": "chaos-elixir-vase",
    # La Hán set (arhat-)
    "tuong-la-han-moc-hon": "arhat-wood-soul",
    "tuong-la-han-hoa-vi": "arhat-fire-tail",
    "tuong-la-han-thuy-linh": "arhat-water-spirit",
    "tuong-la-han-kim-cuong": "arhat-diamond",
    "tuong-la-han-tho-coc": "arhat-earth-grain",
    "tuong-la-han-hon-coc": "arhat-soul-grain",
    "tuong-la-han-tram-huong": "arhat-agarwood",
    "tuong-la-han-phong-vu": "arhat-wind-rain",
    "tuong-la-han-loi-dinh": "arhat-thunderbolt",
    "tuong-la-han-vo-tranh": "arhat-uncontested",
    "tuong-la-han-bat-hoai": "arhat-indestructible",
    "tuong-la-han-van-phap": "arhat-myriad-laws",
    "tuong-la-han-hon-nguyen": "arhat-primordial-chaos",
    "tuong-la-han-cuu-tieu": "arhat-nine-heavens",
    "tuong-la-han-diem-vuong": "arhat-yama",
    "tuong-la-han-thien-dang": "arhat-heavenly-lamp",
    "tuong-la-han-bo-de": "arhat-bodhi",
    "tuong-la-han-sa-mon": "arhat-shramana",
}

# ---------------------------------------------------------------------------
# uniques (co-vat.csv) -- 30
# ---------------------------------------------------------------------------
uniques = {
    "truong-ton-ngo-khong": "sun-wukong-staff",
    "guong-bat-quai": "bagua-mirror",
    "linh-duong-den-long": "lantern-spirit-path",
    "luoi-hai-thien-ly": "thousand-mile-scythe",
    "ban-do-son-ha": "landscape-map",
    "dan-lu-can-khon": "cosmos-furnace",
    "mat-na-hac-bach": "black-white-mask",
    "nghien-muc-suong": "dew-inkstone",
    "bua-tu-vi": "ziwei-talisman",
    "quat-phong-loi": "wind-thunder-fan",
    "tuong-phat-a-di-da": "amitabha-statue",
    "chuong-dai-hong": "great-bell",
    "ao-ca-sa-cuu-pham": "nine-grade-kasaya",
    "dan-lo-thien-lenh": "heaven-decree-furnace",
    "tinh-tam-linh-chau": "pure-heart-bead",
    "loi-phu-co": "ancient-thunder-charm",
    "linh-hoa-bich-bao": "jade-spirit-flower",
    "trong-dong-dong-son": "dong-son-bronze-drum",
    "vong-co-to-phu": "ancestral-necklace",
    "den-tinh-thien-ha": "galaxy-lantern",
    "mat-nien-doan-menh": "doomed-short-life-charm",
    "hon-nguyen-ngoc-chau": "primordial-jade-bead",
    "bach-cot-lenh": "white-bone-decree",
    "tu-hon-linh-bao": "death-soul-box",
    "cuu-u-hac-dan": "nine-abyss-black-elixir",
    "bua-hac-bach-vo-thuong": "black-white-impermanence-charm",
    "co-long-hon-ngoc": "ancient-dragon-soul-jade",
    "dinh-phuong-linh-vi": "phoenix-tail-cauldron",
    "tam-ma-mat-na": "corruption-mask",
    "hon-nguyen-hac-dan": "primordial-black-elixir",
}

# ---------------------------------------------------------------------------
# affixesPrefix (affix-prefix.csv) -- 80
# ---------------------------------------------------------------------------
affixesPrefix = {
    "cuong-bao": "frenzy",
    "liet-hoa": "raging-fire",
    "hung-han": "ferocious",
    "tam-sinh": "triple-birth",
    "huy-diet": "annihilation",
    "khac-tinh": "nemesis",
    "sam-set": "thunderclap",
    "pha-niem": "armor-break",
    "tu-vong-aura": "death-aura",
    "co-long-khoi": "ancient-dragon-rise",
    "bao-phong": "storm-surge",
    "lieu-lam": "reckless",
    "thien-truong": "endless-stack",
    "vu-bao": "earth-storm",
    "thanh-long-noi-gian": "azure-dragon-wrath",
    "ham-bang-sat-khi": "frost-killing-intent",
    "hac-quy-no-gian": "black-tortoise-fury",
    "ngu-hanh-bien": "wuxing-shift",
    "thiet-phi-phong": "iron-swift-wind",
    "bach-hoa-tam-tien": "hundred-fire-immortal",
    "dinh-diem-crit": "peak-crit",
    "vu-luc-cuong": "charged-might",
    "thien-kiep-khang": "lightning-resist-power",
    "hung-than-ac-sat": "fierce-god-slaughter",
    "van-chieu-qui-ton": "myriad-summon-honor",
    "phan-lich": "recoil-force",
    "song-phi-nhan": "twin-flying-blade",
    "thao-nguyen-phi-hoa": "grassland-petal-storm",
    "bien-hoa-lan-song": "water-wave-burst",
    "luc-tram-thu": "green-earth-quagmire",
    "but-mat-phi-tien": "flying-ink-strike",
    "hoang-kim-sat-khi": "golden-killing-intent",
    "tu-quy-xung-ki": "four-ghost-charge",
    "cam-lo-bung-no": "nectar-burst",
    "mat-troi-le-nam": "southern-sun-tear",
    "sat-khi-tam-ma": "corruption-killing-intent",
    "hai-quan-xung-tien": "sea-crest-surge",
    "nham-pha-va-cham": "rock-shatter-impact",
    "hung-man-cuong-bao": "savage-frenzy",
    "bo-luc-the-nang": "potential-force",
    "xuyen-qua-buoc": "piercing-step",
    "ngu-hanh-tuong-khac-cuong": "wuxing-counter-power",
    "van-li-phong-hoa": "thousand-mile-firewind",
    "hoa-cuong-khoi-no": "fire-frenzy-blast",
    "nguyen-luc-phan-xa": "force-ricochet",
    "phi-toc": "swift-speed",
    "than-long-khi": "dragon-spirit-qi",
    "nham-cuong-kieu": "rock-arrogant-might",
    "sat-thach-xung": "stone-shatter-charge",
    "thuy-cuong-han-ngu": "frost-water-control",
    "bich-loi-thien-han": "azure-thunder-frost",
    "moc-linh-song-hoa": "wood-spirit-wave",
    "thien-am-cuong": "thunder-sound-frenzy",
    "hung-man-ba-pha": "savage-crit-burst",
    "kich-bao-lieu-lam": "desperate-frenzy",
    "thu-hoa-vo-thuong": "fire-harvest-impermanence",
    "bach-loi-tan-sat": "hundred-thunder-split",
    "kinh-thien-dong-dia": "earth-shaking-might",
    "cao-truong-toan-thang": "victory-stack",
    "nhat-cuong-van-binh": "lone-power",
    "vu-khi-toan-sat": "all-element-slaughter",
    "tat-dieu-bung-chay": "blazing-corruption-bane",
    "song-long-hop-bich": "twin-dragon-union",
    "ngu-hanh-chuyen-hoa-cuong": "wuxing-convert-power",
    "huong-thinh-kim-cuong": "metal-pierce-might",
    "phi-tieu-toc-sat": "dart-speed-kill",
    "thanh-lam-bien-hoa": "verdant-transform",
    "tho-than-bung-no": "earth-god-blast",
    "xa-thu-toan-nang": "master-archer",
    "pha-than-van-quoc": "early-strike-might",
    "cuong-han-bach-bang": "frenzy-frost-ice",
    "bach-hoa-phung-linh": "hundred-fire-phoenix",
    "thien-nham-cuong-luc": "heaven-rock-might",
    "pha-giap-liet-hoa": "armor-break-blaze",
    "vo-vi-pha-cu": "void-breaker",
    "tam-ma-sat-thu": "corruption-assassin",
    "vo-luong-cuong-sat": "boundless-slaughter",
    "cuong-long-khi-quyen": "dragon-charge-fist",
    "thien-pha-van-tinh": "star-shatter",
    "ngo-hanh-tri-mang": "first-strike-lethal",
}

# ---------------------------------------------------------------------------
# affixesSuffix (affix-suffix.csv) -- 80
# ---------------------------------------------------------------------------
affixesSuffix = {
    "hap-luc": "attraction",
    "cham-bo": "slow-step",
    "lan-truyen": "spread",
    "xich-lien": "chain-link",
    "co-dinh": "anchored",
    "tang-tru": "charge-store",
    "hoi-phuc": "recovery",
    "dan-lu-tinh": "furnace-stack",
    "vo-hieu-hoa": "nullify",
    "phong-an-bao": "seal-guard",
    "ky-nguyen": "lucky-fate",
    "tich-luy-tinh-hoa": "essence-hoard",
    "bao-dan-luu": "elixir-flow",
    "phong-an-an-toan": "seal-safety",
    "phong-an-thang": "seal-ascend",
    "phong-an-khang-pha": "seal-anti-break",
    "phong-an-tam-ma": "seal-corruption-bane",
    "phong-an-no-luc": "seal-effort",
    "phong-an-bao-toan": "seal-preserve",
    "tru-lam-bao-ve": "grove-guard",
    "kien-co-thanh-luy": "fortress-bulwark",
    "an-dinh-hoa": "stabilize",
    "bat-dong": "immovable",
    "chong-nhiem-khi": "infection-resist",
    "khang-thien-kiep": "lightning-resist",
    "giam-soc": "shock-absorb",
    "ben-vung-thu": "sturdy-guard",
    "on-dinh-nen": "stable-base",
    "sinh-luc-hoan-nguyen": "vitality-restore",
    "cam-lo-hoi-phuc": "nectar-recovery",
    "truong-sinh-noi-khi": "longevity-inner-qi",
    "hoi-sinh-ngoai-luc": "revive-force",
    "hap-thu-linh-luc": "orb-absorb",
    "roi-ngau-nhien-dan": "random-reagent-drop",
    "tiet-kiem-dan-duoc": "reagent-thrift",
    "tinh-hoa-vong": "essence-ring",
    "dan-phap-tai-sinh": "elixir-method-rebirth",
    "cu-tuyen-dan-duoc": "reagent-select",
    "khac-tam-ma-chi": "corruption-suppress",
    "tinh-tam-khang": "pure-heart-resist",
    "tan-tam-ma": "corruption-disperse",
    "khang-u-minh": "underworld-resist",
    "bao-ve-tam-ma-thu": "corruption-guard",
    "diep-tinh-tam-ma": "corruption-essence-bane",
    "vo-nguyen-to-hoa": "elementless",
    "toc-do-cuong-luc": "speed-force",
    "tang-toc-hop": "accelerate-box",
    "thien-loi-tang-toc": "thunder-accelerate",
    "phi-toc-giao-diem": "swift-junction",
    "lan-song-dai": "great-wave-spread",
    "song-sot-tang-truong": "survival-growth",
    "bao-ve-linh-dan": "elixir-protect",
    "co-dinh-nguyen-to": "element-lock",
    "hap-luc-lon": "great-attraction",
    "giam-rui-ro-phong-an": "seal-risk-reduce",
    "tang-chon-dan-duoc": "reagent-choice",
    "tu-sinh-phu": "wood-spawn-aid",
    "nhuong-bo-on-dinh": "yield-stability",
    "trao-doi-tim-hiet": "essence-exchange",
    "phu-phuc-linh-khi": "item-revive",
    "song-hit-chain": "twin-hit-chain",
    "ngu-hanh-lien-hoan": "wuxing-chain",
    "song-cuong-nha": "fierce-wave",
    "dong-giao-ngo": "kindred-meeting",
    "luu-giu-toc-do": "speed-retain",
    "han-che-tam-ma-aura": "corruption-limit-aura",
    "gian-soc-khang": "shock-resist-heal",
    "tich-nang-bat-dong": "stored-energy-still",
    "vo-cuc-dung-hoa": "void-fusion",
    "giam-nguyen-lieu-phi": "catalyst-cost-reduce",
    "phi-toc-lien-tiep": "consecutive-speed",
    "yen-tinh-noi-luc": "tranquil-inner-force",
    "tao-luc-song": "wave-pull",
    "phan-xa-khi": "reflect-qi",
    "bien-the-linh-luc": "orb-transmute",
    "tang-truong-tiep-noi": "continuous-growth",
    "giam-thiet-hai-nen": "base-damage-reduce",
    "dong-hanh-tuong-sinh": "kindred-generation",
    "luu-giu-dan-duoc-roi": "reagent-stash-retain",
    "phong-toa-tinh-hoa": "essence-guarantee",
}

# ---------------------------------------------------------------------------
# affixesImplicit (affix-implicit.csv) -- 30
# ---------------------------------------------------------------------------
affixesImplicit = {
    "chuong-song-day": "bell-push-wave",
    "chuong-am-vang": "bell-echo",
    "chuong-chuyen-hoa": "bell-convert",
    "den-chuyen-hoa": "lantern-convert",
    "den-nguyen-to-chuyen": "lantern-element-cycle",
    "den-roi-lech": "lantern-deflect",
    "tuong-tu-linh-aura": "statue-four-spirit-aura",
    "tuong-than-thu": "statue-beast-guard",
    "tuong-on-dinh": "statue-stabilize",
    "bua-mot-lan": "talisman-once",
    "bua-mo-rong": "talisman-expand",
    "bua-tich-luy": "talisman-charge",
    "chau-hap-thu": "bead-absorb",
    "chau-day-chuoi": "bead-chain",
    "chau-xung-nang": "bead-energy-burst",
    "kiem-phan-doi": "sword-split",
    "kiem-xuyen-pha": "sword-pierce",
    "dao-chop-giat": "saber-lightning",
    "dao-tang-toc": "saber-accelerate",
    "nghien-muc-vet-thuong": "inkstone-wound-trail",
    "nghien-muc-ghi-dau": "inkstone-mark",
    "dinh-no-cham": "cauldron-slow-burst",
    "dinh-phan-ngay-to": "cauldron-element-slow",
    "hop-tru-nang": "box-store-energy",
    "quat-doi-huong": "fan-redirect",
    "canh-hoi-phuc": "branch-recovery",
    "hoa-cham-toc": "flower-slow",
    "binh-hap-chuyen": "vase-absorb-convert",
    "trong-song-am": "drum-sound-wave",
    "phu-tat-dau": "charm-seal-ward",
}

# ---------------------------------------------------------------------------
# reagents (dan-duoc.csv) -- 20
# ---------------------------------------------------------------------------
reagents = {
    "linh-dan": "spirit-elixir",
    "tu-hoan-dan": "purple-cycle-elixir",
    "cuu-chuyen-dan": "nine-turn-elixir",
    "phong-an": "seal",
    "hon-dan": "soul-elixir",
    "co-dan": "ancient-elixir",
    "dan-tay-niem": "identify-elixir",
    "dan-tay-affix": "affix-wash-elixir",
    "tinh-hoa-kim": "metal-essence",
    "tinh-hoa-moc": "wood-essence",
    "tinh-hoa-thuy": "water-essence",
    "tinh-hoa-hoa": "fire-essence",
    "tinh-hoa-tho": "earth-essence",
    "tinh-hoa-toc": "speed-essence",
    "tinh-hoa-kien": "durability-essence",
    "tinh-hoa-menh": "stability-essence",
    "tinh-hoa-khac": "counter-essence",
    "tinh-hoa-sinh": "generation-essence",
    "tinh-hoa-crit": "crit-essence",
    "tinh-hoa-linh": "chain-essence",
}

# ---------------------------------------------------------------------------
# catalysts (nguyen-lieu.csv) -- 30
# ---------------------------------------------------------------------------
catalysts = {
    "hoa-tinh": "fire-crystal",
    "moc-tinh": "wood-crystal",
    "thuy-tinh": "water-crystal",
    "kim-tinh": "metal-crystal",
    "tho-tinh": "earth-crystal",
    "vo-cuc-thach": "void-stone",
    "long-cot": "dragon-bone",
    "linh-hoa": "spirit-flower",
    "tinh-tinh-thach": "star-stone",
    "mua-linh": "spirit-rain",
    "tu-khi": "death-qi",
    "tinh-linh-huong": "pure-spirit-incense",
    "den-troi": "sky-lantern",
    "tam-ma-chau": "corruption-bead",
    "moc-linh-tinh": "wood-spirit-crystal",
    "cuu-chuyen-linh-hoa": "nine-turn-spirit-flower",
    "bi-canh-hon": "secret-realm-soul",
    "sinh-tu-tinh": "life-death-crystal",
    "tam-linh-hon-phach": "soul-spirit-essence",
    "hon-nguyen-khi": "primordial-chaos-qi",
    "long-phung-chau": "dragon-phoenix-bead",
    "tam-ma-hon-co": "corruption-ancient-soul",
    "cuu-long-kim-cot": "nine-dragon-metal-bone",
    "thien-long-cot": "heaven-dragon-bone",
    "hac-long-van-thach": "black-dragon-meteorite",
    "dinh-long-tinh": "peak-dragon-crystal",
    "phong-vu-hon": "wind-rain-soul",
    "co-long-dan": "ancient-dragon-elixir",
    "vo-cuc-long-hon": "void-dragon-soul",
    "hon-nguyen-tam-ma-hon": "primordial-corruption-soul",
}

# ---------------------------------------------------------------------------
# corruptionMods (tam-ma-mod.csv) -- 12
# ---------------------------------------------------------------------------
corruptionMods = {
    "hon-cuong": "frenzied-soul",
    "phong-hoa": "sealed-slot",
    "u-minh": "underworld-dark",
    "huyet-sat": "blood-slaughter",
    "vo-luong": "boundless-swarm",
    "ta-dao": "heretic-path",
    "cuong-phong": "violent-wind",
    "lanh-bang": "frozen-ice",
    "dai-khac": "great-counter",
    "thien-le": "heaven-tears",
    "tam-ma-ngu-hanh": "corruption-wuxing",
    "hon-nguyen-bien": "primordial-shift",
}

# ---------------------------------------------------------------------------
# equipment (lo-part.csv) -- 50
# ---------------------------------------------------------------------------
equipment = {
    "dinh-pham": "crown-common",
    "dinh-linh-hoa": "crown-magic-fire",
    "dinh-bao-thien": "crown-rare-heaven",
    "dinh-than-vo-cuc": "crown-legendary-void",
    "dinh-thien-long-quan": "crown-heaven-dragon",
    "than-pham": "body-common",
    "than-linh-moc": "body-magic-wood",
    "than-bao-dan-lu": "body-rare-furnace",
    "than-than-cuu-chuyen": "body-legendary-nine-turn",
    "than-can-khon-dinh-lu": "body-cosmos-furnace",
    "de-pham": "base-common",
    "de-linh-cuu": "base-magic-rescue",
    "de-bao-hoi-tam": "base-rare-return",
    "de-than-thien-ly": "base-legendary-thousand-mile",
    "de-to-dan-bat-hoai": "base-ancestral-indestructible",
    "quai-l-phong-an-toc": "handle-left-seal-swift",
    "quai-l-hoi-sinh-phu": "handle-left-revive-charm",
    "quai-l-tinh-tam-phu": "handle-left-pure-heart-charm",
    "quai-l-loi-dinh-phu": "handle-left-thunderbolt-charm",
    "quai-l-ngu-hanh-tran": "handle-left-wuxing-array",
    "quai-r-phong-an-toc": "handle-right-seal-swift",
    "quai-r-hoi-sinh-phu": "handle-right-revive-charm",
    "quai-r-tinh-tam-phu": "handle-right-pure-heart-charm",
    "quai-r-loi-dinh-phu": "handle-right-thunderbolt-charm",
    "quai-r-ngu-hanh-tran": "handle-right-wuxing-array",
    "nap-pham": "lid-common",
    "nap-linh-cuong": "lid-magic-frenzy",
    "nap-bao-thien-co": "lid-rare-heaven-secret",
    "nap-than-dai-dan-bi": "lid-legendary-great-elixir",
    "nap-thien-co-bi-luc": "lid-heaven-secret-record",
    "khac-phu-pham": "amulet-common",
    "khac-phu-linh-tinh": "amulet-magic-essence",
    "khac-phu-bao-dai": "amulet-rare-great",
    "khac-phu-than-thien-menh": "amulet-legendary-heaven-fate",
    "khac-phu-to-su": "amulet-patriarch",
    "do-suong-l-reroll-tiet-kiem": "ring-left-reroll-thrift",
    "do-suong-l-loai-dan-hiem": "ring-left-rare-drop",
    "do-suong-l-tam-ma-khac": "ring-left-corruption-counter",
    "do-suong-l-phong-an-an-toan": "ring-left-seal-safety",
    "do-suong-l-linh-thu-bao-ky": "ring-left-spirit-record",
    "do-suong-r-reroll-tiet-kiem": "ring-right-reroll-thrift",
    "do-suong-r-loai-dan-hiem": "ring-right-rare-drop",
    "do-suong-r-tam-ma-khac": "ring-right-corruption-counter",
    "do-suong-r-phong-an-an-toan": "ring-right-seal-safety",
    "do-suong-r-linh-thu-bao-ky": "ring-right-spirit-record",
    "day-phong-an-pham": "belt-common",
    "day-phong-an-linh-dan-luu": "belt-magic-elixir-flow",
    "day-phong-an-bao-tinh-hoa": "belt-rare-essence",
    "day-phong-an-than-cuu-chuyen": "belt-legendary-nine-turn",
    "day-phong-an-thien-dia-bao-dai": "belt-heaven-earth-treasure",
}

# ---------------------------------------------------------------------------
# setBonuses (set-bonus.json) -- 3
# ---------------------------------------------------------------------------
setBonuses = {
    "tu-linh": "four-spirits",
    "ngu-hanh": "wuxing",
    "thap-bat-la-han": "eighteen-arhats",
}

# ---------------------------------------------------------------------------
# ascendancies (dao-phai.json top-level) -- 5
# ---------------------------------------------------------------------------
ascendancies = {
    "thai-cuc": "tai-chi",
    "cuu-am": "nine-yin",
    "linh-son": "spirit-mountain",
    "tu-vi": "ziwei",
    "vo-cuc": "void",
}

# ---------------------------------------------------------------------------
# ascendancyNodes (dao-phai.json nested node ids) -- 30
# ---------------------------------------------------------------------------
ascendancyNodes = {
    # Thái Cực (tai-chi)
    "thai-cuc-can-bang": "tai-chi-balance",
    "thai-cuc-hoa-khi": "tai-chi-harmony",
    "thai-cuc-thien-can": "tai-chi-heavenly-stems",
    "thai-cuc-trung-dung": "tai-chi-moderation",
    "thai-cuc-am-duong": "tai-chi-yin-yang",
    "thai-cuc-vo-vi-tu-nhien": "tai-chi-natural-wuwei",
    # Cửu Âm (nine-yin)
    "cuu-am-uc-che": "nine-yin-suppress",
    "cuu-am-chuoi-nguyen": "nine-yin-curse-chain",
    "cuu-am-tam-ma-tinh": "nine-yin-corruption-mastery",
    "cuu-am-am-linh": "nine-yin-yin-spirit",
    "cuu-am-vuc-tham": "nine-yin-abyss",
    "cuu-am-nguyen-luc-vo-bien": "nine-yin-boundless-curse",
    # Linh Sơn (spirit-mountain)
    "linh-son-boi-nhan": "spirit-mountain-multiply",
    "linh-son-day-bau": "spirit-mountain-full-vigor",
    "linh-son-moc-linh": "spirit-mountain-wood-spirit",
    "linh-son-von-song": "spirit-mountain-wave-ring",
    "linh-son-van-linh-hoi-tu": "spirit-mountain-myriad-convergence",
    "linh-son-bong-ma-hoa-than": "spirit-mountain-phantom-form",
    # Tử Vi (ziwei)
    "tu-vi-thien-nhan": "ziwei-heaven-eye",
    "tu-vi-van-menh": "ziwei-destiny",
    "tu-vi-co-bac-tinh-thong": "ziwei-gambling-mastery",
    "tu-vi-nghi-le": "ziwei-ritual",
    "tu-vi-dinh-menh": "ziwei-fate-fixed",
    "tu-vi-nguoc-dong-thoi-gian": "ziwei-time-reversal",
    # Vô Cực (void)
    "vo-cuc-bien-dong": "void-fluctuation",
    "vo-cuc-ran-ro": "void-radiance",
    "vo-cuc-may-rui": "void-twin-fortune",
    "vo-cuc-hon-loan": "void-ordered-chaos",
    "vo-cuc-thinh-no": "void-wrath",
    "vo-cuc-bien-hoa-vo-cung": "void-infinite-change",
}

# ---------------------------------------------------------------------------
# passiveNodes (passive-tree.json) -- 150
# Structured: translate element prefix + descriptor, keep structural suffix.
# ---------------------------------------------------------------------------
ELEM = {"kim": "metal", "moc": "wood", "thuy": "water", "hoa": "fire", "tho": "earth"}

passiveNodes = {
    # --- Hoả (fire) ---
    "hoa-notable-junction-hoa": "fire-notable-junction-fire",
    "hoa-keystone-liet-hoa": "fire-keystone-raging-fire",
    "hoa-notable-cuu-tieu-loi": "fire-notable-nine-heavens-thunder",
    "hoa-notable-hoa-khac-kim": "fire-notable-fire-counter-metal",
    "hoa-notable-liet-tam": "fire-notable-blaze-heart",
    "hoa-notable-phung-hoang": "fire-notable-phoenix",
    "hoa-small-hoa-affix-1": "fire-small-fire-affix-1",
    "hoa-small-hoa-anchor-1": "fire-small-fire-anchor-1",
    "hoa-small-hoa-anchor-2": "fire-small-fire-anchor-2",
    "hoa-small-hoa-aoe-1": "fire-small-fire-aoe-1",
    "hoa-small-hoa-aoe-2": "fire-small-fire-aoe-2",
    "hoa-small-hoa-burst-1": "fire-small-fire-burst-1",
    "hoa-small-hoa-burst-2": "fire-small-fire-burst-2",
    "hoa-small-hoa-charge-1": "fire-small-fire-charge-1",
    "hoa-small-hoa-charge-2": "fire-small-fire-charge-2",
    "hoa-small-hoa-ignite-1": "fire-small-fire-ignite-1",
    "hoa-small-hoa-ignite-2": "fire-small-fire-ignite-2",
    "hoa-small-hoa-ignite-dur": "fire-small-fire-ignite-dur",
    "hoa-small-hoa-mult-1": "fire-small-fire-mult-1",
    "hoa-small-hoa-mult-2": "fire-small-fire-mult-2",
    "hoa-small-hoa-purity": "fire-small-fire-purity",
    "hoa-small-hoa-vel-1": "fire-small-fire-vel-1",
    "hoa-small-hoa-vel-2": "fire-small-fire-vel-2",
    "hoa-small-liet-1": "fire-small-blaze-1",
    "hoa-small-liet-2": "fire-small-blaze-2",
    "hoa-small-liet-3": "fire-small-blaze-3",
    "hoa-start": "fire-start",
    "hoa-tho-bridge-1": "fire-earth-bridge-1",
    # --- shared keystones / hubs ---
    "keystone-bat-bai": "keystone-invincible",
    "keystone-co-bac-to": "keystone-grand-gamble",
    "keystone-thien-menh": "keystone-heaven-mandate",
    "keystone-vo-vi": "keystone-wuwei",
    "hub-vo-cuc-1": "hub-void-1",
    "hub-vo-cuc-2": "hub-void-2",
    "hub-vo-cuc-3": "hub-void-3",
    "hub-vo-cuc-4": "hub-void-4",
    "hub-vo-cuc-5": "hub-void-5",
    # --- Kim (metal) ---
    "kim-notable-junction-kim": "metal-notable-junction-metal",
    "kim-keystone-sac-ben": "metal-keystone-sharpness",
    "kim-notable-kim-quang": "metal-notable-metal-light",
    "kim-notable-kim-xuyen": "metal-notable-metal-pierce",
    "kim-notable-thien-loi": "metal-notable-heaven-thunder",
    "kim-notable-tu-sat": "metal-notable-death-kill",
    "kim-small-kim-affix-1": "metal-small-metal-affix-1",
    "kim-small-kim-anchor-1": "metal-small-metal-anchor-1",
    "kim-small-kim-anchor-2": "metal-small-metal-anchor-2",
    "kim-small-kim-bich": "metal-small-metal-jade",
    "kim-small-kim-bich-2": "metal-small-metal-jade-2",
    "kim-small-kim-bich-3": "metal-small-metal-jade-3",
    "kim-small-kim-burst-1": "metal-small-metal-burst-1",
    "kim-small-kim-burst-2": "metal-small-metal-burst-2",
    "kim-small-kim-charge-1": "metal-small-metal-charge-1",
    "kim-small-kim-charge-2": "metal-small-metal-charge-2",
    "kim-small-kim-crit-dmg-1": "metal-small-metal-crit-dmg-1",
    "kim-small-kim-crit-dmg-2": "metal-small-metal-crit-dmg-2",
    "kim-small-kim-pierce-1": "metal-small-metal-pierce-1",
    "kim-small-kim-pierce-2": "metal-small-metal-pierce-2",
    "kim-small-kim-purity": "metal-small-metal-purity",
    "kim-small-kim-velocity-1": "metal-small-metal-velocity-1",
    "kim-small-kim-velocity-2": "metal-small-metal-velocity-2",
    "kim-small-sat-1": "metal-small-kill-1",
    "kim-small-sat-2": "metal-small-kill-2",
    "kim-small-sat-3": "metal-small-kill-3",
    "kim-start": "metal-start",
    "kim-thuy-bridge-1": "metal-water-bridge-1",
    # --- Mộc (wood) ---
    "moc-hoa-bridge-1": "wood-fire-bridge-1",
    "moc-notable-junction-moc": "wood-notable-junction-wood",
    "moc-keystone-sinh-soi": "wood-keystone-proliferate",
    "moc-notable-moc-quality": "wood-notable-wood-quality",
    "moc-notable-sinh-co": "wood-notable-life-engine",
    "moc-notable-thanh-long": "wood-notable-azure-dragon",
    "moc-notable-truong-sinh": "wood-notable-longevity",
    "moc-small-moc-affix-1": "wood-small-wood-affix-1",
    "moc-small-moc-anchor-1": "wood-small-wood-anchor-1",
    "moc-small-moc-anchor-2": "wood-small-wood-anchor-2",
    "moc-small-moc-charge-1": "wood-small-wood-charge-1",
    "moc-small-moc-charge-2": "wood-small-wood-charge-2",
    "moc-small-moc-heal-1": "wood-small-wood-heal-1",
    "moc-small-moc-heal-2": "wood-small-wood-heal-2",
    "moc-small-moc-heal-3": "wood-small-wood-heal-3",
    "moc-small-moc-immune-1": "wood-small-wood-immune-1",
    "moc-small-moc-immune-2": "wood-small-wood-immune-2",
    "moc-small-moc-purity": "wood-small-wood-purity",
    "moc-small-moc-quality-1": "wood-small-wood-quality-1",
    "moc-small-moc-quality-2": "wood-small-wood-quality-2",
    "moc-small-moc-regen-1": "wood-small-wood-regen-1",
    "moc-small-moc-regen-2": "wood-small-wood-regen-2",
    "moc-small-moc-slow-1": "wood-small-wood-slow-1",
    "moc-small-moc-slow-2": "wood-small-wood-slow-2",
    "moc-small-sinh-1": "wood-small-life-1",
    "moc-small-sinh-2": "wood-small-life-2",
    "moc-small-sinh-3": "wood-small-life-3",
    "moc-start": "wood-start",
    # --- Thổ (earth) ---
    "tho-notable-junction-tho": "earth-notable-junction-earth",
    "tho-keystone-trong-son": "earth-keystone-heavy-mountain",
    "tho-kim-bridge-1": "earth-metal-bridge-1",
    "tho-notable-tho-bach-quy": "earth-notable-earth-tortoise",
    "tho-notable-tho-kim-cuong": "earth-notable-earth-diamond",
    "tho-notable-tho-tich-tho": "earth-notable-earth-accumulate",
    "tho-notable-tho-truong-son": "earth-notable-earth-great-mountain",
    "tho-small-tho-affix-1": "earth-small-earth-affix-1",
    "tho-small-tho-anchor-1": "earth-small-earth-anchor-1",
    "tho-small-tho-anchor-2": "earth-small-earth-anchor-2",
    "tho-small-tho-armor-1": "earth-small-earth-armor-1",
    "tho-small-tho-armor-2": "earth-small-earth-armor-2",
    "tho-small-tho-armor-3": "earth-small-earth-armor-3",
    "tho-small-tho-board-1": "earth-small-earth-board-1",
    "tho-small-tho-board-2": "earth-small-earth-board-2",
    "tho-small-tho-charge-1": "earth-small-earth-charge-1",
    "tho-small-tho-charge-2": "earth-small-earth-charge-2",
    "tho-small-tho-phong-1": "earth-small-earth-seal-1",
    "tho-small-tho-phong-2": "earth-small-earth-seal-2",
    "tho-small-tho-purity": "earth-small-earth-purity",
    "tho-small-tho-slow-1": "earth-small-earth-slow-1",
    "tho-small-tho-slow-2": "earth-small-earth-slow-2",
    "tho-small-tho-stab-1": "earth-small-earth-stab-1",
    "tho-small-tho-stab-2": "earth-small-earth-stab-2",
    "tho-small-tho-stab-3": "earth-small-earth-stab-3",
    "tho-small-tho-tho-1": "earth-small-earth-earth-1",
    "tho-small-tho-tho-2": "earth-small-earth-earth-2",
    "tho-start": "earth-start",
    # --- Thuỷ (water) ---
    "thuy-notable-junction-thuy": "water-notable-junction-water",
    "thuy-keystone-thuy-trieu": "water-keystone-tide",
    "keystone-hon-linh": "keystone-soul-spirit",
    "thuy-moc-bridge-1": "water-wood-bridge-1",
    "thuy-notable-huyen-vu": "water-notable-black-tortoise",
    "thuy-notable-thuy-tinh": "water-notable-water-crystal",
    "thuy-notable-thuy-trieu-trieu": "water-notable-water-high-tide",
    "thuy-notable-tinh-tam-tron": "water-notable-pure-heart-full",
    "thuy-small-luu-1": "water-small-flow-1",
    "thuy-small-luu-2": "water-small-flow-2",
    "thuy-small-luu-3": "water-small-flow-3",
    "thuy-small-thuy-affix-1": "water-small-water-affix-1",
    "thuy-small-thuy-anchor-1": "water-small-water-anchor-1",
    "thuy-small-thuy-anchor-2": "water-small-water-anchor-2",
    "thuy-small-thuy-bounce-1": "water-small-water-bounce-1",
    "thuy-small-thuy-bounce-2": "water-small-water-bounce-2",
    "thuy-small-thuy-charge-1": "water-small-water-charge-1",
    "thuy-small-thuy-charge-2": "water-small-water-charge-2",
    "thuy-small-thuy-dispel-1": "water-small-water-dispel-1",
    "thuy-small-thuy-dispel-2": "water-small-water-dispel-2",
    "thuy-small-thuy-hop-1": "water-small-water-box-1",
    "thuy-small-thuy-hop-2": "water-small-water-box-2",
    "thuy-small-thuy-purity": "water-small-water-purity",
    "thuy-small-thuy-redirect-1": "water-small-water-redirect-1",
    "thuy-small-thuy-redirect-2": "water-small-water-redirect-2",
    "thuy-small-thuy-slow-1": "water-small-water-slow-1",
    "thuy-small-thuy-slow-2": "water-small-water-slow-2",
    "thuy-small-thuy-spread-1": "water-small-water-spread-1",
    "thuy-start": "water-start",
}

# ---------------------------------------------------------------------------
# maps (phap-tran/*.json id field) -- 10
# ---------------------------------------------------------------------------
maps = {
    "tieu-chuan": "standard",
    "tu-sinh": "sanctum",
    "hon-nguyen": "marathon",
    "thien-kiep": "lightning",
    "tam-ma": "mirror",
    "co-dan-lo": "ancient-furnace",
    "long-cung": "dragon-palace",
    "cuu-tieu": "nine-heavens",
    "diem-phu": "underworld",
    "vo-cuc": "endless",
}

# ---------------------------------------------------------------------------
fileRenames = {
    "linh-khi.csv": "items.csv",
    "co-vat.csv": "uniques.csv",
    "affix-prefix.csv": "affix-prefix.csv",
    "affix-suffix.csv": "affix-suffix.csv",
    "affix-implicit.csv": "affix-implicit.csv",
    "dan-duoc.csv": "reagents.csv",
    "nguyen-lieu.csv": "catalysts.csv",
    "tam-ma-mod.csv": "corruption-mods.csv",
    "lo-part.csv": "equipment.csv",
    "set-bonus.json": "set-bonuses.json",
    "dao-phai.json": "ascendancies.json",
    "passive-tree.json": "passive-tree.json",
    "phap-tran/": "maps/",
    "phap-tran/tieu-chuan.json": "maps/standard.json",
    "phap-tran/tu-sinh.json": "maps/sanctum.json",
    "phap-tran/hon-nguyen.json": "maps/marathon.json",
    "phap-tran/thien-kiep.json": "maps/lightning.json",
    "phap-tran/tam-ma.json": "maps/mirror.json",
    "phap-tran/co-dan-lo.json": "maps/ancient-furnace.json",
    "phap-tran/long-cung.json": "maps/dragon-palace.json",
    "phap-tran/cuu-tieu.json": "maps/nine-heavens.json",
    "phap-tran/diem-phu.json": "maps/underworld.json",
    "phap-tran/vo-cuc.json": "maps/endless.json",
}

groups = {
    "items": items,
    "uniques": uniques,
    "affixesPrefix": affixesPrefix,
    "affixesSuffix": affixesSuffix,
    "affixesImplicit": affixesImplicit,
    "reagents": reagents,
    "catalysts": catalysts,
    "corruptionMods": corruptionMods,
    "equipment": equipment,
    "setBonuses": setBonuses,
    "ascendancies": ascendancies,
    "ascendancyNodes": ascendancyNodes,
    "passiveNodes": passiveNodes,
    "maps": maps,
}

total = sum(len(g) for g in groups.values())

out = {
    "_meta": {
        "generatedAt": "2026-05-20",
        "totalIds": total,
        "dictionary": "see 2026-05-20-naming-convention-pivot.md",
    },
    "_fileRenames": fileRenames,
}
out.update(groups)

with open(
    "/Users/firegroup/projects/lu-dan-game/tools/content-rename/id-map.json", "w"
) as f:
    json.dump(out, f, ensure_ascii=False, indent=2)
    f.write("\n")

# --- verification ---
slug_re = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
print("=== per-domain counts ===")
for name, g in groups.items():
    vals = list(g.values())
    dups = sorted({v for v in vals if vals.count(v) > 1})
    bad = [v for v in vals if not slug_re.match(v)]
    print(f"{name}: {len(g)}  dups={dups}  bad={bad}")
print(f"GRAND TOTAL = {total}")
print(f"_fileRenames entries = {len(fileRenames)}")
